version: 1.0.0.{build}

platform: Any CPU
configuration: Release

skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
before_build:
  - nuget restore "./src/TestRepository.sln"

build:
  project: src\TestRepository.sln
  publish_nuget: true
  
test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:  
  - path: /.*\.nupkg/
    name: NuGet package
  
deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey 41f5af1a-5d34-42ec-a808-0ad3dcfbcb8d; if ($lastexitcode -ne 0) {throw}}
  
deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: Enbbe1MRpwxTk+l70bA1DfoJq62BO4S01RRKFDL4Fx83I/f3W4D4MQJTRXrNwkFj
    skip_symbols: true
    artifact: /.*\.nupkg/
    on:
      branch: master
  
  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    auth_token:
      secure: F00nbLt278uSgQKKvDMLxc6AXtaZNE4b9WcDfDZ79T1gN23xhpLtoeguU6B0tSuV
    on:
      branch: master
    appveyor_repo_tag: true